package com.tinyrpg.misc 
{
	import flash.display.BitmapData;
	import flash.utils.ByteArray;
	
	import com.tinyrpg.display.attacks.player.*;
	import com.tinyrpg.display.attacks.enemy.*;
	
	import com.tinyrpg.utils.TinyLogManager;
	
	/**
	 * @author jeremyabel
	 */
	public class TinyMoveFXConfig 
	{
		private static const MOVE_ABSORB 				: String = 'ABSORB';
		private static const MOVE_AGILITY 				: String = 'AGILITY';
		private static const MOVE_ANCIENT_POWER 		: String = 'ANCIENT POWER';
		private static const MOVE_ASTONISH				: String = 'ASTONISH';
		private static const MOVE_BITE 					: String = 'BITE';
		private static const MOVE_BLAZE_KICK 			: String = 'BLAZE KICK';
		private static const MOVE_BUBBLE 				: String = 'BUBBLE';
		private static const MOVE_BULK_UP		 		: String = 'BULK UP';
		private static const MOVE_CLAMP 				: String = 'CLAMP';
		private static const MOVE_CONFUSE_RAY			: String = 'CONFUSE RAY';
		private static const MOVE_CONFUSION 			: String = 'CONFUSION';
		private static const MOVE_COSMIC_POWER 			: String = 'COSMIC POWER';
		private static const MOVE_DETECT 				: String = 'DETECT';
		private static const MOVE_DOUBLE_EDGE 			: String = 'DOUBLE EDGE';
		private static const MOVE_DOUBLE_KICK 			: String = 'DOUBLE KICK';
		private static const MOVE_DRAGON_BREATH 		: String = 'DRAGON BREATH';
		private static const MOVE_DRAGON_DANCE 			: String = 'DRAGON DANCE';
		private static const MOVE_DREAM_EATER 			: String = 'DREAM EATER';
		private static const MOVE_DYNAMIC_PUNCH 		: String = 'DYNAMIC PUNCH';
		private static const MOVE_EMBER 				: String = 'EMBER';
		private static const MOVE_EXPLOSION 			: String = 'EXPLOSION';
		private static const MOVE_FAKE_OUT 				: String = 'FAKE OUT';
		private static const MOVE_FAKE_TEARS			: String = 'FAKE TEARS';
		private static const MOVE_FALSE_SWIPE 			: String = 'FALSE SWIPE';
		private static const MOVE_FEINT_ATTACK 			: String = 'FEINT ATTACK';
		private static const MOVE_FIRE_PUNCH 			: String = 'FIRE PUNCH';
		private static const MOVE_FLAMETHROWER 			: String = 'FLAMETHROWER';
		private static const MOVE_FOCUS_ENERGY 			: String = 'FOCUS ENERGY';
		private static const MOVE_FURY_SWIPES 			: String = 'FURY SWIPES';
		private static const MOVE_GROWL 				: String = 'GROWL';
		private static const MOVE_HEAL_BELL 			: String = 'HEAL BELL';
		private static const MOVE_HOWL					: String = 'HOWL';
		private static const MOVE_HYDRO_PUMP 			: String = 'HYDRO PUMP';
		private static const MOVE_HYPER_BEAM 			: String = 'HYPER BEAM';
		private static const MOVE_HYPNOSIS				: String = 'HYPNOSIS';
		private static const MOVE_IRON_DEFENSE			: String = 'IRON DEFENSE'; // Use first half of METAL CLAW, 2x
		private static const MOVE_KARATE_CHOP 			: String = 'KARATE CHOP';
		private static const MOVE_LEAF_BLADE			: String = 'LEAF BLADE';
		private static const MOVE_LEER 					: String = 'LEER';
		private static const MOVE_LICK 					: String = 'LICK';
		private static const MOVE_LOW_KICK 				: String = 'LOW KICK';
		private static const MOVE_LUSTER_PURGE			: String = 'LUSTER PURGE';
		private static const MOVE_MEAN_LOOK 			: String = 'MEAN LOOK';
		private static const MOVE_MEGA_PUNCH 			: String = 'MEGA PUNCH';
		private static const MOVE_METAL_CLAW 			: String = 'METAL CLAW';
		private static const MOVE_METEOR_MASH			: String = 'METEOR MASH';
		private static const MOVE_METRONOME 			: String = 'METRONOME';
		private static const MOVE_MUD_SLAP 				: String = 'MUD SLAP';
		private static const MOVE_MUD_SPORT				: String = 'MUD SPORT';
		private static const MOVE_MUDDY_WATER			: String = 'MUDDY WATER';
		private static const MOVE_NIGHT_SHADE			: String = 'NIGHT SHADE';
		private static const MOVE_POUND 				: String = 'POUND';
		private static const MOVE_PROTECT 				: String = 'PROTECT';
		private static const MOVE_PSYCHIC				: String = 'PSYCHIC';
		private static const MOVE_PSYWAVE				: String = 'PSYWAVE';
		private static const MOVE_QUICK_ATTACK 			: String = 'QUICK ATTACK';
		private static const MOVE_RAIN_DANCE 			: String = 'RAIN DANCE';
		private static const MOVE_RAPID_SPIN 			: String = 'RAPID SPIN';
		private static const MOVE_RECOVER 				: String = 'RECOVER';
		private static const MOVE_REFRESH				: String = 'REFRESH';
		private static const MOVE_REST					: String = 'REST';
		private static const MOVE_SAFEGUARD 			: String = 'SAFEGUARD';
		private static const MOVE_SAND_ATTACK 			: String = 'SAND ATTACK';
		private static const MOVE_SCARY_FACE 			: String = 'SCARY FACE';
		private static const MOVE_SCRATCH 				: String = 'SCRATCH';
		private static const MOVE_SCREECH 				: String = 'SCREECH';
		private static const MOVE_SELF_DESTRUCT 		: String = 'SELF-DESTRUCT';
		private static const MOVE_SLAM 					: String = 'SLAM';
		private static const MOVE_SLASH 				: String = 'SLASH';
		private static const MOVE_SMOG 					: String = 'SMOG';
		private static const MOVE_SMOKESCREEN 			: String = 'SMOKESCREEN';
		private static const MOVE_SNORE 				: String = 'SNORE';
		private static const MOVE_SPITE 				: String = 'SPITE';
		private static const MOVE_STRUGGLE 				: String = 'STRUGGLE';
		private static const MOVE_SUBMISSION			: String = 'SUBMISSION';
		private static const MOVE_SUPERSONIC 			: String = 'SUPERSONIC';
		private static const MOVE_SWIFT 				: String = 'SWIFT';
		private static const MOVE_TACKLE 				: String = 'TACKLE';
		private static const MOVE_TAIL_WHIP				: String = 'TAIL WHIP';
		private static const MOVE_TAKE_DOWN 			: String = 'TAKE-DOWN';
		private static const MOVE_THRASH 				: String = 'THRASH';
		private static const MOVE_THUNDER 				: String = 'THUNDER';
		private static const MOVE_THUNDER_SHOCK 		: String = 'THUNDER SHOCK';
		private static const MOVE_TWISTER 				: String = 'TWISTER';
		private static const MOVE_WATER_GUN 			: String = 'WATER GUN';
		private static const MOVE_WATER_PULSE			: String = 'WATER PULSE';
		private static const MOVE_WATER_SPORT			: String = 'WATER SPORT'; 
		private static const MOVE_WING_ATTACK 			: String = 'WING ATTACK';
		private static const MOVE_WISH					: String = 'WISH';
		
		// Spritesheet XML: Player
		[Embed(source='../../../../bin/xml/MoveFX/player_absorb.xml', mimeType='application/octet-stream')] 			public static const XML_Absorb_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_agility.xml', mimeType='application/octet-stream')] 			public static const XML_Agility_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_ancient_power.xml', mimeType='application/octet-stream')] 		public static const XML_Ancient_Power_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_bite.xml', mimeType='application/octet-stream')] 				public static const XML_Bite_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_blaze_kick.xml', mimeType='application/octet-stream')] 		public static const XML_Blaze_Kick_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_bubble.xml', mimeType='application/octet-stream')] 			public static const XML_Bubble_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_bulk_up.xml', mimeType='application/octet-stream')] 			public static const XML_Bulk_Up_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_clamp.xml', mimeType='application/octet-stream')] 				public static const XML_Clamp_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_confuse_ray.xml', mimeType='application/octet-stream')] 		public static const XML_Confuse_Ray_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_confusion.xml', mimeType='application/octet-stream')] 			public static const XML_Confusion_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_detect.xml', mimeType='application/octet-stream')] 			public static const XML_Detect_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_double_edge.xml', mimeType='application/octet-stream')] 		public static const XML_Double_Edge_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_double_kick.xml', mimeType='application/octet-stream')] 		public static const XML_Double_Kick_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_dragon_breath.xml', mimeType='application/octet-stream')] 		public static const XML_Dragon_Breath_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_dream_eater.xml', mimeType='application/octet-stream')] 		public static const XML_Dream_Eater_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_dynamic_punch.xml', mimeType='application/octet-stream')] 		public static const XML_Dynamic_Punch_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_ember.xml', mimeType='application/octet-stream')] 				public static const XML_Ember_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_explosion.xml', mimeType='application/octet-stream')] 			public static const XML_Explosion_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_false_swipe.xml', mimeType='application/octet-stream')] 		public static const XML_False_Swipe_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_feint_attack.xml', mimeType='application/octet-stream')] 		public static const XML_Feint_Attack_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_fire_punch.xml', mimeType='application/octet-stream')] 		public static const XML_Fire_Punch_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_flamethrower.xml', mimeType='application/octet-stream')] 		public static const XML_Flamethrower_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_focus_energy.xml', mimeType='application/octet-stream')] 		public static const XML_Focus_Energy_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_fury_swipes.xml', mimeType='application/octet-stream')] 		public static const XML_Fury_Swipes_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_growl.xml', mimeType='application/octet-stream')] 				public static const XML_Growl_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_heal_bell.xml', mimeType='application/octet-stream')] 			public static const XML_Heal_Bell_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_howl.xml', mimeType='application/octet-stream')] 				public static const XML_Howl_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_hydro_pump.xml', mimeType='application/octet-stream')] 		public static const XML_Hydro_Pump_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_hyper_beam.xml', mimeType='application/octet-stream')] 		public static const XML_Hyper_Beam_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_hypnosis.xml', mimeType='application/octet-stream')] 			public static const XML_Hypnosis_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_karate_chop.xml', mimeType='application/octet-stream')] 		public static const XML_Karate_Chop_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_leaf_blade.xml', mimeType='application/octet-stream')] 		public static const XML_Leaf_Blade_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_leer.xml', mimeType='application/octet-stream')] 				public static const XML_Leer_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_lick.xml', mimeType='application/octet-stream')] 				public static const XML_Lick_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_low_kick.xml', mimeType='application/octet-stream')] 			public static const XML_Low_Kick_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_luster_purge.xml', mimeType='application/octet-stream')] 		public static const XML_Luster_Purge_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_mean_look.xml', mimeType='application/octet-stream')] 			public static const XML_Mean_Look_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_mega_punch.xml', mimeType='application/octet-stream')] 		public static const XML_Mega_Punch_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_metal_claw.xml', mimeType='application/octet-stream')] 		public static const XML_Metal_Claw_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_metronome.xml', mimeType='application/octet-stream')] 			public static const XML_Metronome_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_mud_slap.xml', mimeType='application/octet-stream')] 			public static const XML_Mud_Slap_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_muddy_water.xml', mimeType='application/octet-stream')] 		public static const XML_Muddy_Water_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_night_shade.xml', mimeType='application/octet-stream')] 		public static const XML_Night_Shade_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_pound.xml', mimeType='application/octet-stream')] 				public static const XML_Pound_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_protect.xml', mimeType='application/octet-stream')] 			public static const XML_Protect_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_psychic.xml', mimeType='application/octet-stream')] 			public static const XML_Psychic_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_psywave.xml', mimeType='application/octet-stream')] 			public static const XML_Psywave_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_quick_attack.xml', mimeType='application/octet-stream')] 		public static const XML_Quick_Attack_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_rain_dance.xml', mimeType='application/octet-stream')] 		public static const XML_Rain_Dance_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_rapid_spin.xml', mimeType='application/octet-stream')] 		public static const XML_Rapid_Spin_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_recover.xml', mimeType='application/octet-stream')] 			public static const XML_Recover_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_rest.xml', mimeType='application/octet-stream')] 				public static const XML_Rest_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_safeguard.xml', mimeType='application/octet-stream')] 			public static const XML_Safeguard_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_sand_attack.xml', mimeType='application/octet-stream')] 		public static const XML_Sand_Attack_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_scary_face.xml', mimeType='application/octet-stream')] 		public static const XML_Scary_Face_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_scratch.xml', mimeType='application/octet-stream')] 			public static const XML_Scratch_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_screech.xml', mimeType='application/octet-stream')] 			public static const XML_Screech_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_self_destruct.xml', mimeType='application/octet-stream')] 		public static const XML_Self_Destruct_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_slam.xml', mimeType='application/octet-stream')] 				public static const XML_Slam_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_slash.xml', mimeType='application/octet-stream')] 				public static const XML_Slash_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_smog.xml', mimeType='application/octet-stream')] 				public static const XML_Smog_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_smokescreen.xml', mimeType='application/octet-stream')] 		public static const XML_Smokescreen_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_snore.xml', mimeType='application/octet-stream')] 				public static const XML_Snore_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_spite.xml', mimeType='application/octet-stream')] 				public static const XML_Spite_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_struggle.xml', mimeType='application/octet-stream')] 			public static const XML_Struggle_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_submission.xml', mimeType='application/octet-stream')] 		public static const XML_Submission_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_supersonic.xml', mimeType='application/octet-stream')] 		public static const XML_Supersonic_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_swift.xml', mimeType='application/octet-stream')] 				public static const XML_Swift_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_tackle.xml', mimeType='application/octet-stream')] 			public static const XML_Tackle_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_tail_whip.xml', mimeType='application/octet-stream')] 			public static const XML_Tail_Whip_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_take_down.xml', mimeType='application/octet-stream')] 			public static const XML_Take_Down_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_thrash.xml', mimeType='application/octet-stream')] 			public static const XML_Thrash_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_thunder.xml', mimeType='application/octet-stream')] 			public static const XML_Thunder_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_thundershock.xml', mimeType='application/octet-stream')] 		public static const XML_Thundershock_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_twister.xml', mimeType='application/octet-stream')] 			public static const XML_Twister_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_water_gun.xml', mimeType='application/octet-stream')] 			public static const XML_Water_Gun_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_wing_attack.xml', mimeType='application/octet-stream')] 		public static const XML_Wing_Attack_Player : Class;
		[Embed(source='../../../../bin/xml/MoveFX/player_wish.xml', mimeType='application/octet-stream')] 				public static const XML_Wish_Player : Class;
			
		// Spritesheet XML: Enemy
		[Embed(source='../../../../bin/xml/MoveFX/enemy_absorb.xml', mimeType='application/octet-stream')] 				public static const XML_Absorb_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_agility.xml', mimeType='application/octet-stream')] 			public static const XML_Agility_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_ancient_power.xml', mimeType='application/octet-stream')] 		public static const XML_Ancient_Power_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_bite.xml', mimeType='application/octet-stream')] 				public static const XML_Bite_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_blaze_kick.xml', mimeType='application/octet-stream')] 			public static const XML_Blaze_Kick_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_bubble.xml', mimeType='application/octet-stream')] 				public static const XML_Bubble_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_bulk_up.xml', mimeType='application/octet-stream')] 			public static const XML_Bulk_Up_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_clamp.xml', mimeType='application/octet-stream')] 				public static const XML_Clamp_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_confuse_ray.xml', mimeType='application/octet-stream')] 		public static const XML_Confuse_Ray_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_confusion.xml', mimeType='application/octet-stream')] 			public static const XML_Confusion_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_detect.xml', mimeType='application/octet-stream')] 				public static const XML_Detect_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_double_edge.xml', mimeType='application/octet-stream')] 		public static const XML_Double_Edge_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_double_kick.xml', mimeType='application/octet-stream')] 		public static const XML_Double_Kick_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_dragon_breath.xml', mimeType='application/octet-stream')] 		public static const XML_Dragon_Breath_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_dream_eater.xml', mimeType='application/octet-stream')] 		public static const XML_Dream_Eater_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_dynamic_punch.xml', mimeType='application/octet-stream')] 		public static const XML_Dynamic_Punch_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_ember.xml', mimeType='application/octet-stream')] 				public static const XML_Ember_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_explosion.xml', mimeType='application/octet-stream')] 			public static const XML_Explosion_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_false_swipe.xml', mimeType='application/octet-stream')] 		public static const XML_False_Swipe_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_feint_attack.xml', mimeType='application/octet-stream')] 		public static const XML_Feint_Attack_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_fire_punch.xml', mimeType='application/octet-stream')] 			public static const XML_Fire_Punch_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_flamethrower.xml', mimeType='application/octet-stream')] 		public static const XML_Flamethrower_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_focus_energy.xml', mimeType='application/octet-stream')] 		public static const XML_Focus_Energy_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_fury_swipes.xml', mimeType='application/octet-stream')] 		public static const XML_Fury_Swipes_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_growl.xml', mimeType='application/octet-stream')] 				public static const XML_Growl_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_heal_bell.xml', mimeType='application/octet-stream')] 			public static const XML_Heal_Bell_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_howl.xml', mimeType='application/octet-stream')] 				public static const XML_Howl_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_hydro_pump.xml', mimeType='application/octet-stream')] 			public static const XML_Hydro_Pump_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_hyper_beam.xml', mimeType='application/octet-stream')] 			public static const XML_Hyper_Beam_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_hypnosis.xml', mimeType='application/octet-stream')] 			public static const XML_Hypnosis_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_karate_chop.xml', mimeType='application/octet-stream')] 		public static const XML_Karate_Chop_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_leaf_blade.xml', mimeType='application/octet-stream')] 			public static const XML_Leaf_Blade_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_leer.xml', mimeType='application/octet-stream')] 				public static const XML_Leer_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_lick.xml', mimeType='application/octet-stream')] 				public static const XML_Lick_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_low_kick.xml', mimeType='application/octet-stream')] 			public static const XML_Low_Kick_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_luster_purge.xml', mimeType='application/octet-stream')] 		public static const XML_Luster_Purge_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_mean_look.xml', mimeType='application/octet-stream')] 			public static const XML_Mean_Look_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_mega_punch.xml', mimeType='application/octet-stream')] 			public static const XML_Mega_Punch_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_metal_claw.xml', mimeType='application/octet-stream')] 			public static const XML_Metal_Claw_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_metronome.xml', mimeType='application/octet-stream')] 			public static const XML_Metronome_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_mud_slap.xml', mimeType='application/octet-stream')] 			public static const XML_Mud_Slap_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_muddy_water.xml', mimeType='application/octet-stream')] 		public static const XML_Muddy_Water_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_night_shade.xml', mimeType='application/octet-stream')] 		public static const XML_Night_Shade_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_pound.xml', mimeType='application/octet-stream')] 				public static const XML_Pound_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_protect.xml', mimeType='application/octet-stream')] 			public static const XML_Protect_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_psychic.xml', mimeType='application/octet-stream')] 			public static const XML_Psychic_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_psywave.xml', mimeType='application/octet-stream')] 			public static const XML_Psywave_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_quick_attack.xml', mimeType='application/octet-stream')] 		public static const XML_Quick_Attack_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_rain_dance.xml', mimeType='application/octet-stream')] 			public static const XML_Rain_Dance_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_rapid_spin.xml', mimeType='application/octet-stream')] 			public static const XML_Rapid_Spin_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_recover.xml', mimeType='application/octet-stream')] 			public static const XML_Recover_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_rest.xml', mimeType='application/octet-stream')] 				public static const XML_Rest_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_safeguard.xml', mimeType='application/octet-stream')] 			public static const XML_Safeguard_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_sand_attack.xml', mimeType='application/octet-stream')] 		public static const XML_Sand_Attack_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_scary_face.xml', mimeType='application/octet-stream')] 			public static const XML_Scary_Face_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_scratch.xml', mimeType='application/octet-stream')] 			public static const XML_Scratch_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_screech.xml', mimeType='application/octet-stream')] 			public static const XML_Screech_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_self_destruct.xml', mimeType='application/octet-stream')] 		public static const XML_Self_Destruct_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_slam.xml', mimeType='application/octet-stream')] 				public static const XML_Slam_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_slash.xml', mimeType='application/octet-stream')] 				public static const XML_Slash_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_smog.xml', mimeType='application/octet-stream')] 				public static const XML_Smog_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_smokescreen.xml', mimeType='application/octet-stream')] 		public static const XML_Smokescreen_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_snore.xml', mimeType='application/octet-stream')] 				public static const XML_Snore_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_spite.xml', mimeType='application/octet-stream')] 				public static const XML_Spite_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_struggle.xml', mimeType='application/octet-stream')] 			public static const XML_Struggle_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_submission.xml', mimeType='application/octet-stream')] 			public static const XML_Submission_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_supersonic.xml', mimeType='application/octet-stream')] 			public static const XML_Supersonic_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_swift.xml', mimeType='application/octet-stream')] 				public static const XML_Swift_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_tackle.xml', mimeType='application/octet-stream')] 				public static const XML_Tackle_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_tail_whip.xml', mimeType='application/octet-stream')] 			public static const XML_Tail_Whip_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_take_down.xml', mimeType='application/octet-stream')] 			public static const XML_Take_Down_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_thrash.xml', mimeType='application/octet-stream')] 				public static const XML_Thrash_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_thunder.xml', mimeType='application/octet-stream')] 			public static const XML_Thunder_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_thundershock.xml', mimeType='application/octet-stream')] 		public static const XML_Thundershock_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_twister.xml', mimeType='application/octet-stream')] 			public static const XML_Twister_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_water_gun.xml', mimeType='application/octet-stream')] 			public static const XML_Water_Gun_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_wing_attack.xml', mimeType='application/octet-stream')] 		public static const XML_Wing_Attack_Enemy : Class;
		[Embed(source='../../../../bin/xml/MoveFX/enemy_wish.xml', mimeType='application/octet-stream')] 				public static const XML_Wish_Enemy : Class;
		
		public static function getMoveFXXML( name: String, isEnemy : Boolean ) : XML
		{
			TinyLogManager.log('getMoveFXXML: ' + name, null);
			
			var newXMLBytes : ByteArray;
			
			switch ( name.toUpperCase() )
			{
				default:
				case MOVE_ABSORB 			: newXMLBytes = ( isEnemy ? new XML_Absorb_Enemy : new XML_Absorb_Player ) as ByteArray; break;
				case MOVE_AGILITY 			: newXMLBytes = ( isEnemy ? new XML_Agility_Enemy : new XML_Agility_Player ) as ByteArray; break;
				case MOVE_ANCIENT_POWER 	: newXMLBytes = ( isEnemy ? new XML_Ancient_Power_Enemy : new XML_Ancient_Power_Player ) as ByteArray; break;
				case MOVE_ASTONISH			: newXMLBytes = ( isEnemy ? new XML_Focus_Energy_Enemy : new XML_Focus_Energy_Player ) as ByteArray; break;
				case MOVE_BITE 				: newXMLBytes = ( isEnemy ? new XML_Bite_Enemy : new XML_Bite_Player ) as ByteArray; break;
				case MOVE_BLAZE_KICK 		: newXMLBytes = ( isEnemy ? new XML_Blaze_Kick_Enemy : new XML_Blaze_Kick_Player ) as ByteArray; break;
				case MOVE_BUBBLE 			: newXMLBytes = ( isEnemy ? new XML_Bubble_Enemy : new XML_Bubble_Player ) as ByteArray; break;
				case MOVE_BULK_UP			: newXMLBytes = ( isEnemy ? new XML_Bulk_Up_Enemy : new XML_Bulk_Up_Player ) as ByteArray; break;
				case MOVE_CLAMP 			: newXMLBytes = ( isEnemy ? new XML_Clamp_Enemy : new XML_Clamp_Player ) as ByteArray; break;
				case MOVE_CONFUSE_RAY 		: newXMLBytes = ( isEnemy ? new XML_Confuse_Ray_Enemy : new XML_Confuse_Ray_Player ) as ByteArray; break;
				case MOVE_CONFUSION 		: newXMLBytes = ( isEnemy ? new XML_Confusion_Enemy : new XML_Confusion_Player ) as ByteArray; break;
				case MOVE_COSMIC_POWER		: newXMLBytes = ( isEnemy ? new XML_Rain_Dance_Enemy : new XML_Rain_Dance_Player ) as ByteArray; break;
				case MOVE_DETECT 			: newXMLBytes = ( isEnemy ? new XML_Detect_Enemy : new XML_Detect_Player ) as ByteArray; break;
				case MOVE_DOUBLE_EDGE 		: newXMLBytes = ( isEnemy ? new XML_Double_Edge_Enemy : new XML_Double_Edge_Player ) as ByteArray; break;
				case MOVE_DOUBLE_KICK 		: newXMLBytes = ( isEnemy ? new XML_Double_Kick_Enemy : new XML_Double_Kick_Player ) as ByteArray; break;
				case MOVE_DRAGON_BREATH 	: newXMLBytes = ( isEnemy ? new XML_Dragon_Breath_Enemy : new XML_Dragon_Breath_Player ) as ByteArray; break;
				case MOVE_DRAGON_DANCE		: newXMLBytes = ( isEnemy ? new XML_Confusion_Enemy : new XML_Confusion_Player ) as ByteArray; break;
				case MOVE_DREAM_EATER 		: newXMLBytes = ( isEnemy ? new XML_Dream_Eater_Enemy : new XML_Dream_Eater_Player ) as ByteArray; break;
				case MOVE_DYNAMIC_PUNCH 	: newXMLBytes = ( isEnemy ? new XML_Dynamic_Punch_Enemy : new XML_Dynamic_Punch_Player ) as ByteArray; break;
				case MOVE_EMBER 			: newXMLBytes = ( isEnemy ? new XML_Ember_Enemy : new XML_Ember_Player ) as ByteArray; break;
				case MOVE_EXPLOSION 		: newXMLBytes = ( isEnemy ? new XML_Explosion_Enemy : new XML_Explosion_Player ) as ByteArray; break;
				case MOVE_FALSE_SWIPE 		: newXMLBytes = ( isEnemy ? new XML_False_Swipe_Enemy : new XML_False_Swipe_Player ) as ByteArray; break;
				case MOVE_FEINT_ATTACK 		: newXMLBytes = ( isEnemy ? new XML_Feint_Attack_Enemy : new XML_Feint_Attack_Player ) as ByteArray; break;
				case MOVE_FIRE_PUNCH 		: newXMLBytes = ( isEnemy ? new XML_Fire_Punch_Enemy : new XML_Fire_Punch_Player ) as ByteArray; break;
				case MOVE_FLAMETHROWER 		: newXMLBytes = ( isEnemy ? new XML_Flamethrower_Enemy : new XML_Flamethrower_Player ) as ByteArray; break;
				case MOVE_FOCUS_ENERGY		: newXMLBytes = ( isEnemy ? new XML_Focus_Energy_Enemy : new XML_Focus_Energy_Player ) as ByteArray; break;
				case MOVE_FURY_SWIPES		: newXMLBytes = ( isEnemy ? new XML_Fury_Swipes_Enemy : new XML_Fury_Swipes_Player ) as ByteArray; break;
				case MOVE_GROWL				: newXMLBytes = ( isEnemy ? new XML_Growl_Enemy : new XML_Growl_Player ) as ByteArray; break;
				case MOVE_HEAL_BELL			: newXMLBytes = ( isEnemy ? new XML_Heal_Bell_Enemy : new XML_Heal_Bell_Player ) as ByteArray; break;
				case MOVE_HOWL				: newXMLBytes = ( isEnemy ? new XML_Howl_Enemy : new XML_Howl_Player ) as ByteArray; break;
				case MOVE_HYDRO_PUMP 		: newXMLBytes = ( isEnemy ? new XML_Hydro_Pump_Enemy : new XML_Hydro_Pump_Player ) as ByteArray; break;
				case MOVE_HYPER_BEAM 		: newXMLBytes = ( isEnemy ? new XML_Hyper_Beam_Enemy : new XML_Hyper_Beam_Player ) as ByteArray; break;
				case MOVE_HYPNOSIS			: newXMLBytes = ( isEnemy ? new XML_Hypnosis_Enemy : new XML_Hypnosis_Player ) as ByteArray; break;
				case MOVE_KARATE_CHOP 		: newXMLBytes = ( isEnemy ? new XML_Karate_Chop_Enemy : new XML_Karate_Chop_Player ) as ByteArray; break;
				case MOVE_LEAF_BLADE 		: newXMLBytes = ( isEnemy ? new XML_Leaf_Blade_Enemy : new XML_Leaf_Blade_Player ) as ByteArray; break;
				case MOVE_LEER 				: newXMLBytes = ( isEnemy ? new XML_Leer_Enemy : new XML_Leer_Player ) as ByteArray; break;
				case MOVE_LICK 				: newXMLBytes = ( isEnemy ? new XML_Lick_Enemy : new XML_Lick_Player ) as ByteArray; break;
				case MOVE_LOW_KICK 			: newXMLBytes = ( isEnemy ? new XML_Low_Kick_Enemy : new XML_Low_Kick_Player ) as ByteArray; break;
				case MOVE_LUSTER_PURGE		: newXMLBytes = ( isEnemy ? new XML_Luster_Purge_Enemy : new XML_Luster_Purge_Player ) as ByteArray; break;
				case MOVE_MEAN_LOOK 		: newXMLBytes = ( isEnemy ? new XML_Mean_Look_Enemy : new XML_Mean_Look_Player ) as ByteArray; break;
				case MOVE_MEGA_PUNCH 		: newXMLBytes = ( isEnemy ? new XML_Mega_Punch_Enemy : new XML_Mega_Punch_Player ) as ByteArray; break;
				case MOVE_METAL_CLAW 		: newXMLBytes = ( isEnemy ? new XML_Metal_Claw_Enemy : new XML_Metal_Claw_Player ) as ByteArray; break;
				case MOVE_METEOR_MASH		: newXMLBytes = ( isEnemy ? new XML_Rain_Dance_Enemy : new XML_Rain_Dance_Player ) as ByteArray; break;
				case MOVE_METRONOME 		: newXMLBytes = ( isEnemy ? new XML_Metronome_Enemy : new XML_Metronome_Player ) as ByteArray; break;
				case MOVE_MUD_SLAP 			: newXMLBytes = ( isEnemy ? new XML_Mud_Slap_Enemy : new XML_Mud_Slap_Player ) as ByteArray; break;
				case MOVE_MUD_SPORT 		: newXMLBytes = ( isEnemy ? new XML_Hydro_Pump_Player : new XML_Hydro_Pump_Enemy ) as ByteArray; break;
				case MOVE_MUDDY_WATER 		: newXMLBytes = ( isEnemy ? new XML_Muddy_Water_Enemy : new XML_Muddy_Water_Player ) as ByteArray; break;
				case MOVE_NIGHT_SHADE 		: newXMLBytes = ( isEnemy ? new XML_Night_Shade_Enemy : new XML_Night_Shade_Player ) as ByteArray; break;
				case MOVE_POUND 			: newXMLBytes = ( isEnemy ? new XML_Pound_Enemy : new XML_Pound_Player ) as ByteArray; break;
				case MOVE_PROTECT 			: newXMLBytes = ( isEnemy ? new XML_Protect_Enemy : new XML_Protect_Player ) as ByteArray; break;
				case MOVE_PSYCHIC 			: newXMLBytes = ( isEnemy ? new XML_Psychic_Enemy : new XML_Psychic_Player ) as ByteArray; break;
				case MOVE_PSYWAVE 			: newXMLBytes = ( isEnemy ? new XML_Psywave_Enemy : new XML_Psywave_Player ) as ByteArray; break;
				case MOVE_QUICK_ATTACK 		: newXMLBytes = ( isEnemy ? new XML_Quick_Attack_Enemy : new XML_Quick_Attack_Player ) as ByteArray; break;
				case MOVE_RAIN_DANCE 		: newXMLBytes = ( isEnemy ? new XML_Rain_Dance_Enemy : new XML_Rain_Dance_Player ) as ByteArray; break;
				case MOVE_RAPID_SPIN 		: newXMLBytes = ( isEnemy ? new XML_Rapid_Spin_Enemy : new XML_Rapid_Spin_Player ) as ByteArray; break;
				case MOVE_RECOVER 			: newXMLBytes = ( isEnemy ? new XML_Recover_Enemy : new XML_Recover_Player ) as ByteArray; break;
				case MOVE_REST 				: newXMLBytes = ( isEnemy ? new XML_Rest_Enemy : new XML_Rest_Player ) as ByteArray; break;
				case MOVE_SAFEGUARD 		: newXMLBytes = ( isEnemy ? new XML_Safeguard_Enemy : new XML_Safeguard_Player ) as ByteArray; break;
				case MOVE_SAND_ATTACK 		: newXMLBytes = ( isEnemy ? new XML_Sand_Attack_Enemy : new XML_Sand_Attack_Player ) as ByteArray; break;
				case MOVE_SCARY_FACE 		: newXMLBytes = ( isEnemy ? new XML_Scary_Face_Enemy : new XML_Scary_Face_Player ) as ByteArray; break;
				case MOVE_SCRATCH 			: newXMLBytes = ( isEnemy ? new XML_Scratch_Enemy : new XML_Scratch_Player ) as ByteArray; break;
				case MOVE_SCREECH 			: newXMLBytes = ( isEnemy ? new XML_Screech_Enemy : new XML_Screech_Player ) as ByteArray; break;
				case MOVE_SELF_DESTRUCT 	: newXMLBytes = ( isEnemy ? new XML_Self_Destruct_Enemy : new XML_Self_Destruct_Player ) as ByteArray; break;
				case MOVE_SLAM 				: newXMLBytes = ( isEnemy ? new XML_Slam_Enemy : new XML_Slam_Player ) as ByteArray; break;
				case MOVE_SLASH 			: newXMLBytes = ( isEnemy ? new XML_Slash_Enemy : new XML_Slash_Player ) as ByteArray; break;
				case MOVE_SMOG 				: newXMLBytes = ( isEnemy ? new XML_Smog_Enemy : new XML_Smog_Player ) as ByteArray; break;
				case MOVE_SMOKESCREEN 		: newXMLBytes = ( isEnemy ? new XML_Smokescreen_Enemy : new XML_Smokescreen_Player ) as ByteArray; break;
				case MOVE_SNORE 			: newXMLBytes = ( isEnemy ? new XML_Snore_Enemy : new XML_Snore_Player ) as ByteArray; break;
				case MOVE_SPITE 			: newXMLBytes = ( isEnemy ? new XML_Spite_Enemy : new XML_Spite_Player ) as ByteArray; break;
				case MOVE_STRUGGLE 			: newXMLBytes = ( isEnemy ? new XML_Struggle_Enemy : new XML_Struggle_Player ) as ByteArray; break;
				case MOVE_SUBMISSION 		: newXMLBytes = ( isEnemy ? new XML_Submission_Enemy : new XML_Submission_Player ) as ByteArray; break;
				case MOVE_SUPERSONIC 		: newXMLBytes = ( isEnemy ? new XML_Supersonic_Enemy : new XML_Supersonic_Player ) as ByteArray; break;
				case MOVE_SWIFT 			: newXMLBytes = ( isEnemy ? new XML_Swift_Enemy : new XML_Swift_Player ) as ByteArray; break;
				case MOVE_TACKLE	 		: newXMLBytes = ( isEnemy ? new XML_Tackle_Enemy : new XML_Tackle_Player ) as ByteArray; break;
				case MOVE_TAIL_WHIP 		: newXMLBytes = ( isEnemy ? new XML_Tail_Whip_Enemy : new XML_Tail_Whip_Player ) as ByteArray; break;
				case MOVE_TAKE_DOWN		 	: newXMLBytes = ( isEnemy ? new XML_Take_Down_Enemy : new XML_Take_Down_Player ) as ByteArray; break;
				case MOVE_THRASH 			: newXMLBytes = ( isEnemy ? new XML_Thrash_Enemy : new XML_Thrash_Player ) as ByteArray; break;
				case MOVE_THUNDER 			: newXMLBytes = ( isEnemy ? new XML_Thunder_Enemy : new XML_Thunder_Player ) as ByteArray; break;
				case MOVE_THUNDER_SHOCK	 	: newXMLBytes = ( isEnemy ? new XML_Thundershock_Enemy : new XML_Thundershock_Player ) as ByteArray; break;
				case MOVE_TWISTER 			: newXMLBytes = ( isEnemy ? new XML_Twister_Enemy : new XML_Twister_Player ) as ByteArray; break;
				case MOVE_WATER_GUN 		: newXMLBytes = ( isEnemy ? new XML_Water_Gun_Enemy : new XML_Water_Gun_Player ) as ByteArray; break;
				case MOVE_WATER_SPORT 		: newXMLBytes = ( isEnemy ? new XML_Hydro_Pump_Player : new XML_Hydro_Pump_Enemy ) as ByteArray; break;
				case MOVE_WATER_PULSE		: newXMLBytes = ( isEnemy ? new XML_Supersonic_Enemy : new XML_Supersonic_Player ) as ByteArray; break;
				case MOVE_WING_ATTACK 		: newXMLBytes = ( isEnemy ? new XML_Wing_Attack_Enemy : new XML_Wing_Attack_Player ) as ByteArray; break;
				case MOVE_WISH				: newXMLBytes = ( isEnemy ? new XML_Wish_Enemy : new XML_Wish_Player ) as ByteArray; break;
			}
			
			var string : String = newXMLBytes.readUTFBytes( newXMLBytes.length );			
			return new XML( string );			
		}
		
		
		public static function getMoveFXSprite( name : String, isEnemy : Boolean ) : BitmapData
		{
			TinyLogManager.log('getMoveFXSprite: ' + name, null);
			
			var newSprite : BitmapData;
			
			switch ( name.toUpperCase() ) 
			{
				default:
				case MOVE_ABSORB: 				newSprite = isEnemy ? new AbsorbEnemy : new AbsorbPlayer; break;
				case MOVE_AGILITY: 				newSprite = isEnemy ? new AgilityEnemy : new AgilityPlayer; break;
				case MOVE_ANCIENT_POWER: 		newSprite = isEnemy ? new AncientPowerEnemy : new AncientPowerPlayer; break;
				case MOVE_ASTONISH:				newSprite = isEnemy ? new FocusEnergyEnemy : new FocusEnergyPlayer; break;
				case MOVE_BITE: 				newSprite = isEnemy ? new BiteEnemy : new BitePlayer; break;
				case MOVE_BLAZE_KICK:			newSprite = isEnemy ? new BlazeKickEnemy : new BlazeKickPlayer; break;
				case MOVE_BUBBLE:				newSprite = isEnemy ? new BubbleEnemy : new BubblePlayer; break;
				case MOVE_BULK_UP:				newSprite = isEnemy ? new BulkUpEnemy: new BulkUpPlayer; break;
				case MOVE_CLAMP:				newSprite = isEnemy ? new ClampEnemy : new ClampPlayer; break;
				case MOVE_CONFUSION:			newSprite = isEnemy ? new ConfusionEnemy : new ConfusionPlayer; break;
				case MOVE_CONFUSE_RAY:			newSprite = isEnemy ? new ConfuseRayEnemy : new ConfuseRayPlayer; break;
				case MOVE_COSMIC_POWER:			newSprite = isEnemy ? new CosmicPowerEnemy : new CosmicPowerPlayer; break;
				case MOVE_DETECT:				newSprite = isEnemy ? new DetectEnemy : new DetectPlayer; break;
				case MOVE_DOUBLE_EDGE:			newSprite = isEnemy ? new DoubleEdgeEnemy : new DoubleEdgePlayer; break;
				case MOVE_DOUBLE_KICK:			newSprite = isEnemy ? new DoubleKickEnemy : new DoubleKickPlayer; break;
				case MOVE_DRAGON_BREATH:		newSprite = isEnemy ? new DragonBreathEnemy : new DragonBreathPlayer; break;
				case MOVE_DRAGON_DANCE:			newSprite = isEnemy ? new ConfusionEnemy : new ConfusionPlayer; break;
				case MOVE_DREAM_EATER:			newSprite = isEnemy ? new DreamEaterEnemy : new DreamEaterPlayer; break;
				case MOVE_DYNAMIC_PUNCH:		newSprite = isEnemy ? new DynamicPunchEnemy : new DynamicPunchPlayer; break;
				case MOVE_EMBER:				newSprite = isEnemy ? new EmberEnemy : new EmberPlayer; break;
				case MOVE_EXPLOSION:			newSprite = isEnemy ? new ExplosionEnemy : new ExplosionPlayer; break;
				case MOVE_FALSE_SWIPE:			newSprite = isEnemy ? new FalseSwipeEnemy : new FalseSwipePlayer; break;
				case MOVE_FEINT_ATTACK:			newSprite = isEnemy ? new FeintAttackEnemy : new FeintAttackPlayer; break;
				case MOVE_FIRE_PUNCH:			newSprite = isEnemy ? new FirePunchEnemy : new FirePunchPlayer; break;
				case MOVE_FLAMETHROWER:			newSprite = isEnemy ? new FlamethrowerEnemy : new FlamethrowerPlayer; break;
				case MOVE_FOCUS_ENERGY:			newSprite = isEnemy ? new FocusEnergyEnemy : new FocusEnergyPlayer; break;
				case MOVE_FURY_SWIPES:			newSprite = isEnemy ? new FurySwipesEnemy : new FurySwipesPlayer; break;
				case MOVE_GROWL:				newSprite = isEnemy ? new GrowlEnemy : new GrowlPlayer; break;
				case MOVE_HEAL_BELL:			newSprite = isEnemy ? new HealBellEnemy : new HealBellPlayer; break;
				case MOVE_HOWL:					newSprite = isEnemy ? new HowlEnemy : new HowlPlayer; break;
				case MOVE_HYDRO_PUMP:			newSprite = isEnemy ? new HydroPumpEnemy : new HydroPumpPlayer; break;
				case MOVE_HYPER_BEAM:			newSprite = isEnemy ? new HyperBeamEnemy : new HyperBeamPlayer; break;
				case MOVE_HYPNOSIS:				newSprite = isEnemy ? new HypnosisEnemy : new HypnosisPlayer; break;
				case MOVE_KARATE_CHOP:			newSprite = isEnemy ? new KarateChopEnemy : new KarateChopPlayer; break;
				case MOVE_LEAF_BLADE:			newSprite = isEnemy ? new LeafBladeEnemy : new LeafBladePlayer; break;
				case MOVE_LEER:					newSprite = isEnemy ? new LeerEnemy : new LeerPlayer; break;
				case MOVE_LICK:					newSprite = isEnemy ? new LickEnemy : new LickPlayer; break;
				case MOVE_LOW_KICK:				newSprite = isEnemy ? new LowKickEnemy : new LowKickPlayer; break;
				case MOVE_LUSTER_PURGE:			newSprite = isEnemy ? new LusterPurgeEnemy : new LusterPurgePlayer; break;
				case MOVE_MEAN_LOOK:			newSprite = isEnemy ? new MeanLookEnemy : new MeanLookPlayer; break;
				case MOVE_MEGA_PUNCH:			newSprite = isEnemy ? new MegaPunchEnemy : new MegaPunchPlayer; break;
				case MOVE_METAL_CLAW:			newSprite = isEnemy ? new MetalClawEnemy : new MetalClawPlayer; break;
				case MOVE_METEOR_MASH:			newSprite = isEnemy ? new MeteorMashEnemy : new MeteorMashPlayer; break;
				case MOVE_METRONOME:			newSprite = isEnemy ? new MetronomeEnemy : new MetronomePlayer; break;
				case MOVE_MUD_SLAP:				newSprite = isEnemy ? new MudSlapEnemy : new MudSlapPlayer; break;
				case MOVE_MUD_SPORT:			newSprite = isEnemy ? new MudSportEnemy : new MudSportPlayer; break;
				case MOVE_MUDDY_WATER:			newSprite = isEnemy ? new MuddyWaterEnemy : new MuddyWaterPlayer; break;
				case MOVE_NIGHT_SHADE:			newSprite = isEnemy ? new NightShadeEnemy : new NightShadePlayer; break;
				case MOVE_PSYCHIC:				newSprite = isEnemy ? new PsychicEnemy : new PsychicPlayer; break;
				case MOVE_PSYWAVE:				newSprite = isEnemy ? new PsywaveEnemy : new PsywavePlayer; break;
				case MOVE_POUND:				newSprite = isEnemy ? new PoundEnemy : new PoundPlayer; break;
				case MOVE_PROTECT:				newSprite = isEnemy ? new ProtectEnemy : new ProtectPlayer; break;
				case MOVE_QUICK_ATTACK:			newSprite = isEnemy ? new QuickAttackEnemy : new QuickAttackPlayer; break;
				case MOVE_RAIN_DANCE:			newSprite = isEnemy ? new RainDanceEnemy : new RainDancePlayer; break;
				case MOVE_RAPID_SPIN:			newSprite = isEnemy ? new RapidSpinEnemy : new RapidSpinPlayer; break;
				case MOVE_RECOVER:				newSprite = isEnemy ? new RecoverEnemy : new RecoverPlayer; break;
				case MOVE_REST:					newSprite = isEnemy ? new RestEnemy : new RestPlayer; break;
				case MOVE_SAFEGUARD:			newSprite = isEnemy ? new SafeguardEnemy : new SafeguardPlayer; break;
				case MOVE_SAND_ATTACK:			newSprite = isEnemy ? new SandAttackEnemy : new SandAttackPlayer; break;
				case MOVE_SCARY_FACE:			newSprite = isEnemy ? new ScaryFaceEnemy : new ScaryFacePlayer; break;
				case MOVE_SCRATCH:				newSprite = isEnemy ? new ScratchEnemy : new ScratchPlayer; break;
				case MOVE_SCREECH:				newSprite = isEnemy ? new ScreechEnemy : new ScreechPlayer; break;
				case MOVE_SELF_DESTRUCT:		newSprite = isEnemy ? new SelfDestructEnemy : new SelfDestructPlayer; break;
				case MOVE_SLAM:					newSprite = isEnemy ? new SlamEnemy : new SlamPlayer; break;
				case MOVE_SLASH:				newSprite = isEnemy ? new SlashEnemy: new SlashPlayer; break;
				case MOVE_SMOG:					newSprite = isEnemy ? new SmogEnemy : new SmogPlayer; break;
				case MOVE_SMOKESCREEN:			newSprite = isEnemy ? new SmokescreenEnemy : new SmokescreenPlayer; break;
				case MOVE_SNORE:				newSprite = isEnemy ? new SnoreEnemy : new SnorePlayer; break;
				case MOVE_SPITE:				newSprite = isEnemy ? new SpiteEnemy : new SpitePlayer; break;
				case MOVE_STRUGGLE: 			newSprite = isEnemy ? new StruggleEnemy : new StrugglePlayer; break;
				case MOVE_SUBMISSION: 			newSprite = isEnemy ? new SubmissionEnemy : new SubmissionPlayer; break;
				case MOVE_SUPERSONIC:			newSprite = isEnemy ? new SupersonicEnemy : new SupersonicPlayer; break;
				case MOVE_SWIFT:				newSprite = isEnemy ? new SwiftEnemy : new SwiftPlayer; break;
				case MOVE_TACKLE:				newSprite = isEnemy ? new TackleEnemy : new TacklePlayer; break;
				case MOVE_TAIL_WHIP:			newSprite = isEnemy ? new TailWhipEnemy : new TailWhipPlayer; break;
				case MOVE_TAKE_DOWN:			newSprite = isEnemy ? new TakeDownEnemy : new TakeDownPlayer; break;
				case MOVE_THRASH:				newSprite = isEnemy ? new ThrashEnemy : new ThrashPlayer; break;
				case MOVE_THUNDER:				newSprite = isEnemy ? new ThunderEnemy : new ThunderPlayer; break;
				case MOVE_THUNDER_SHOCK:		newSprite = isEnemy ? new ThundershockEnemy : new ThundershockPlayer; break;
				case MOVE_TWISTER:				newSprite = isEnemy ? new TwisterEnemy : new TwisterPlayer; break;
				case MOVE_WATER_GUN: 			newSprite = isEnemy ? new WaterGunEnemy : new WaterGunPlayer; break;
				case MOVE_WATER_PULSE: 			newSprite = isEnemy ? new WaterPulseEnemy : new WaterPulsePlayer; break;
				case MOVE_WATER_SPORT: 			newSprite = isEnemy ? new HydroPumpPlayer : new HydroPumpEnemy; break;
				case MOVE_WING_ATTACK:			newSprite = isEnemy ? new WingAttackEnemy : new WingAttackPlayer; break;
				case MOVE_WISH:					newSprite = isEnemy ? new WishEnemy: new WishPlayer; break;
			}
			
			return newSprite;
		}
		
		
		public static function getMoveAdjustY( name : String, isEnemy : Boolean ) : int
		{
			TinyLogManager.log('getMoveAdjustY: ' + name, null);
			
			var yOffset : int = 0;
			
			switch ( name.toUpperCase() ) 
			{
				default:
				case MOVE_ABSORB: 				yOffset = isEnemy ? 0 : 0; break;
				case MOVE_AGILITY: 				yOffset = isEnemy ? 0 : 0; break;
				case MOVE_ANCIENT_POWER: 		yOffset = isEnemy ? 0 : -4; break;
				case MOVE_ASTONISH:		 		yOffset = isEnemy ? 0 : 4; break;
				case MOVE_BITE: 				yOffset = isEnemy ? 0 : -10; break;
				case MOVE_BLAZE_KICK:			yOffset = isEnemy ? 0 : -8; break;
				case MOVE_BUBBLE:				yOffset = isEnemy ? 0 : -10; break;
				case MOVE_BULK_UP:				yOffset = isEnemy ? 0 : -8; break;
				case MOVE_CLAMP:				yOffset = isEnemy ? 0 : -10; break;
				case MOVE_CONFUSION:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_CONFUSE_RAY:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_COSMIC_POWER:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_DETECT:				yOffset = isEnemy ? 0 : 0; break;
				case MOVE_DOUBLE_EDGE:			yOffset = isEnemy ? 0 : -4; break;
				case MOVE_DOUBLE_KICK:			yOffset = isEnemy ? 0 : -4; break;
				case MOVE_DRAGON_BREATH:		yOffset = isEnemy ? 0 : -4; break;
				case MOVE_DREAM_EATER:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_DYNAMIC_PUNCH:		yOffset = isEnemy ? 0 : -4; break;
				case MOVE_EMBER:				yOffset = isEnemy ? 0 : -6; break;
				case MOVE_EXPLOSION:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_FALSE_SWIPE:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_FEINT_ATTACK:			yOffset = isEnemy ? 0 : -4; break;
				case MOVE_FIRE_PUNCH:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_FLAMETHROWER:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_FOCUS_ENERGY:			yOffset = isEnemy ? 0 : 4; break;
				case MOVE_FURY_SWIPES:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_GROWL:				yOffset = isEnemy ? -8 : -4; break;
				case MOVE_HEAL_BELL:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_HOWL:					yOffset = isEnemy ? -8 : -4; break;
				case MOVE_HYDRO_PUMP:			yOffset = isEnemy ? 2 : 0; break;
				case MOVE_HYPER_BEAM:			yOffset = isEnemy ? -6 : -8; break;
				case MOVE_HYPNOSIS:				yOffset = isEnemy ? -2 : -2; break;
				case MOVE_KARATE_CHOP:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_LEAF_BLADE:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_LEER:					yOffset = isEnemy ? 0 : 0; break;
				case MOVE_LICK:					yOffset = isEnemy ? 0 : -8; break;
				case MOVE_LOW_KICK:				yOffset = isEnemy ? 0 : -4; break;
				case MOVE_LUSTER_PURGE:			yOffset = isEnemy ? -12 : 6; break;
				case MOVE_MEAN_LOOK:			yOffset = isEnemy ? 0 : -2; break;
				case MOVE_MEGA_PUNCH:			yOffset = isEnemy ? 0 : -8; break;
				case MOVE_METAL_CLAW:			yOffset = isEnemy ? 0 : 2; break;
				case MOVE_METEOR_MASH:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_METRONOME:			yOffset = isEnemy ? 0 : -4; break;
				case MOVE_MUD_SLAP:				yOffset = isEnemy ? 0 : -6; break;
				case MOVE_MUD_SPORT:			yOffset = isEnemy ? -2 : 2; break;
				case MOVE_MUDDY_WATER:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_NIGHT_SHADE:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_PSYCHIC:				yOffset = isEnemy ? 0 : -6; break;
				case MOVE_PSYWAVE:				yOffset = isEnemy ? 0 : -6; break;
				case MOVE_POUND:				yOffset = isEnemy ? 0 : -6; break;
				case MOVE_PROTECT:				yOffset = isEnemy ? -12 : 0; break;
				case MOVE_QUICK_ATTACK:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_RAIN_DANCE:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_RAPID_SPIN:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_RECOVER:				yOffset = isEnemy ? -6 : 0; break;
				case MOVE_REST:					yOffset = isEnemy ? 0 : -2; break;
				case MOVE_SAFEGUARD:			yOffset = isEnemy ? -12 : 0; break;
				case MOVE_SAND_ATTACK:			yOffset = isEnemy ? 0 : -8; break;
				case MOVE_SCARY_FACE:			yOffset = isEnemy ? 0 : -4; break;
				case MOVE_SCRATCH:				yOffset = isEnemy ? 0 : -4; break;
				case MOVE_SCREECH:				yOffset = isEnemy ? 0 : -4; break;
				case MOVE_SELF_DESTRUCT:		yOffset = isEnemy ? -6 : 0; break;
				case MOVE_SLAM:					yOffset = isEnemy ? 0 : -4; break;
				case MOVE_SLASH:				yOffset = isEnemy ? 0 : -8; break;
				case MOVE_SMOG:					yOffset = isEnemy ? 0 : 0; break;
				case MOVE_SMOKESCREEN:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_SNORE:				yOffset = isEnemy ? -6 : -4; break;
				case MOVE_SPITE:				yOffset = isEnemy ? 0 : 0; break;
				case MOVE_STRUGGLE: 			yOffset = isEnemy ? 0 : -4; break;
				case MOVE_SUBMISSION: 			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_SUPERSONIC:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_SWIFT:				yOffset = isEnemy ? 0 : 0; break;
				case MOVE_TACKLE:				yOffset = isEnemy ? 0 : -4; break;
				case MOVE_TAIL_WHIP:			yOffset = isEnemy ? 0 : 0; break;
				case MOVE_TAKE_DOWN:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_THRASH:				yOffset = isEnemy ? 0 : -10; break;
				case MOVE_THUNDER:				yOffset = isEnemy ? 2 : 0; break;
				case MOVE_THUNDER_SHOCK:		yOffset = isEnemy ? 0 : -10; break;
				case MOVE_TWISTER:				yOffset = isEnemy ? 2 : 0; break;
				case MOVE_WATER_GUN: 			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_WATER_PULSE: 			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_WATER_SPORT: 			yOffset = isEnemy ? -2 : 2; break;
				case MOVE_WING_ATTACK:			yOffset = isEnemy ? 0 : -6; break;
				case MOVE_WISH:					yOffset = isEnemy ? 0 : 0; break;
			}
			
			return yOffset;
		}				
	}
}
